[package]
name = "audio_samples_python"
version = "0.2.3"
edition = "2024"
description = "Python bindings for high-performance AudioSamples Rust ecosystem - fast, type-safe audio processing with automatic metadata coordination"
repository = "https://github.com/jmg049/audio_samples_python"
homepage = "https://github.com/jmg049/audio_samples_python"
documentation = "https://docs.rs/audio_samples_python"
authors = ["Jack Geraghty (jmg049) <jgeraghty049@gmail.com>"]
readme = "README.md"
license = "MIT"
keywords = ["audio", "python", "bindings", "signal-processing", "multimedia"]
categories = ["multimedia::audio", "api-bindings"]
include = [
    "src/**/*",
    "Cargo.toml",
    "README.md",
    "LICENSE",
    "*.pyi",
    "audio_samples/*.pyi",
    "audio_samples/py.typed",
    "logo.png",
]

[lib]
name = "audio_samples"
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.17.1"
pyo3 = { version = "0.28", features = [
    "extension-module",
    "multiple-pymethods",
    "experimental-inspect",
] }
audio_samples = { version = "1.0.6", features = [
    "python", "full_no_plotting"
] }
audio_samples_io = { version = "0.2.0", features = ["wav", "numpy", "flac"] }
numpy = "0.28"
serde_json = "1.0.149"
spectrograms = { version = "1.4.0", features = ["python"] }
non-empty-slice = "0.5.1"
num-complex = "0.4"

[features]
default = []
audio-samples-plotting = ["audio_samples/plotting"]
simd = ["audio_samples/simd"]
flac-parallel = ["audio_samples_io/flac-parallel"]

[profile.release]
opt-level = 3
debug = false
lto = "thin"
codegen-units = 1
panic = "unwind"
